FROM ubuntu:bionic
MAINTAINER Daniel Goude <daniel@goude.se>
EXPOSE 22

RUN \
  export DEBIAN_FRONTEND=noninteractive && \
  apt-get update && \
  apt-get install -y \
%packages%
  apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9 && \
  add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran35/' && \
  add-apt-repository ppa:neovim-ppa/stable && \
  apt-get update && \
  apt-get install -y neovim r-base && \
  mkdir -p /var/run/sshd && \
  locale-gen en_US.UTF-8 && \
  useradd -ms /usr/bin/zsh runcom && \
  echo "runcom:runcom" | chpasswd && \
  adduser runcom sudo && \
  apt-get clean && \
  echo "developer-linux ubuntu:bionic $(date --iso-8601=seconds)" >> /home/runcom/.runcom-log && \
  chown runcom:runcom /home/runcom/.runcom-log
