FROM goude/base-linux
MAINTAINER Daniel Goude <daniel@goude.se>

# Developer packages
# --no-install-recommends \
RUN \
  apt-get update && \
  apt-get install -y \
    nodejs nodejs-legacy npm \
    python-dev \
    python3-dev python3-pip python3-venv \
    python3-matplotlib python3-pandas

