# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #config.vm.box = "ubuntu/xenial64"
  config.vm.box = "bento/ubuntu-16.04"
  config.ssh.forward_agent = true
  config.vm.network "forwarded_port", guest: 1313, host: 1313
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.network "forwarded_port", guest: 8889, host: 8889
  config.vm.network "forwarded_port", guest: 8890, host: 8890
  config.vm.network "forwarded_port", guest: 18353, host: 18353
  #config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    #vb.gui = true
    vb.name = "dev-machine-ubuntu"
    vb.memory = "4096"
    # Customize the amount of memory on the VM:
    #vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
      echo Running provisioning script...

      add-apt-repository ppa:neovim-ppa/stable
      apt-get update

      # essentials
      apt-get install -y \
        apt-transport-https \
        build-essential \
        ca-certificates \
        cmake \
        git \
        hdevtools \
        linux-image-extra-$(uname -r) \
        linux-image-extra-virtual \
        software-properties-common \
        tlsdate \
        tmux \
        vim-nox \
        zsh \
        exuberant-ctags \
        silversearcher-ag \
        curl \
        htop \
        jq \
        neovim \
        tree \
        libbz2-dev \
        libreadline-dev \
        libsqlite3-dev \
        libssl-dev \
        libxml2-dev \
        libxslt-dev \
        ghc \
        pandoc \
        python-dev \
        python3-cairo \
        python3-dev \
        python3-lxml \
        python3-matplotlib \
        python3-pandas \
        python3-pip \
        python3-venv

      # Docker
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

      add-apt-repository \
         "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
         $(lsb_release -cs) \
         stable"

      apt-get update
      apt-get install -y docker-ce

      gpasswd -a vagrant docker

      # Get setup files for next stage.
      git clone https://github.com/goude/runcom /tmp/runcom

      echo Done.
  SHELL
end
