# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #if Vagrant.has_plugin?("vagrant-proxyconf")
  #config.proxy.http     = ""
  #config.proxy.https    = ""
  #config.proxy.no_proxy = "localhost,127.0.0.1"
  #end

  config.vm.box = "bento/ubuntu-18.04"
  config.ssh.forward_agent = true

  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.network "forwarded_port", guest: 8889, host: 8889
  config.vm.network "forwarded_port", guest: 18353, host: 18353

  #config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    #vb.gui = true
    vb.name = "dev-machine-ubuntu"
    vb.memory = "4096"

    # Enable if DNS problems
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  config.vm.provision "shell", path: "../provision.sh"
end
