#!/bin/bash
function prompt_parse_git_branch {
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

function prompt_ls_output {
    filecount=$(ls -al | grep "^-" | wc -l)
    dircount=$(ls -al | grep "^d" | wc -l)
    echo "${filecount}|${dircount}"
}

function prompt_build { 
    local C_BASE="\[\033[01;36m\]" 
    local C_GRAY="\[\033[00;37m\]" 
    local C_RESET="\[\033[00m\]"
    export PS1="\n$C_BASE\A \u@\h \$(prompt_parse_git_branch) $C_RESET\n[\!] \w $C_GRAY\$$C_RESET " 
}

prompt_build 

